// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api_dotnet.Data;

#nullable disable

namespace api_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api_dotnet.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("api_dotnet.Models.Midia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlMidia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Midias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "",
                            Nome = "Música A",
                            UrlMidia = "https://teste.com/musicaA.mp3"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "",
                            Nome = "Música B",
                            UrlMidia = "https://teste.com/musicaB.mp3"
                        });
                });

            modelBuilder.Entity("api_dotnet.Models.MidiaPlaylist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<int>("MidiaId")
                        .HasColumnType("integer");

                    b.Property<bool>("ExibirNoPlayer")
                        .HasColumnType("boolean");

                    b.HasKey("PlaylistId", "MidiaId");

                    b.HasIndex("MidiaId");

                    b.ToTable("MidiaPlaylists");

                    b.HasData(
                        new
                        {
                            PlaylistId = 1,
                            MidiaId = 1,
                            ExibirNoPlayer = false
                        },
                        new
                        {
                            PlaylistId = 1,
                            MidiaId = 2,
                            ExibirNoPlayer = false
                        });
                });

            modelBuilder.Entity("api_dotnet.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Favoritas"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Trilha Sonora"
                        });
                });

            modelBuilder.Entity("api_dotnet.Models.MidiaPlaylist", b =>
                {
                    b.HasOne("api_dotnet.Models.Midia", "Midia")
                        .WithMany("Playlists")
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_dotnet.Models.Playlist", "Playlist")
                        .WithMany("Midias")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("api_dotnet.Models.Midia", b =>
                {
                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("api_dotnet.Models.Playlist", b =>
                {
                    b.Navigation("Midias");
                });
#pragma warning restore 612, 618
        }
    }
}
